name: Build Debug APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Unzip project
        run: |
          ZIP_FILE=$(find . -maxdepth 1 -name "*.zip" | head -n 1)
          if [ -n "$ZIP_FILE" ]; then
            echo "Extracting $ZIP_FILE"
            unzip -o "$ZIP_FILE" -d extracted
          else
            echo "No zip file found"
          fi

      - name: Find and move to project
        run: |
          GRADLEW=$(find . -name "gradlew" | head -n 1)
          echo "Found gradlew at: $GRADLEW"
          PROJECT_DIR=$(dirname "$GRADLEW")
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x ${{ env.PROJECT_DIR }}/gradlew

      - name: Generate debug keystore
        run: |
          keytool -genkey -v -keystore debug.keystore \
            -storepass android -alias androiddebugkey -keypass android \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.1.0

      - name: Build debug APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: akshor-posha-debug-apk
          path: |
            **/app/build/outputs/apk/debug/*.apk
